version: "2.1"

services:
  powerdns-admin:
    build:
      context: .
      dockerfile: docker-test/Dockerfile
    image: powerdns-admin-test
    container_name: powerdns-admin-test
    ports:
      - "9191:80"
    networks:
      - default
    env_file:
      - ./docker-test/env
    depends_on:
      - pdns-server

  pdns-server:
    build:
      context: .
      dockerfile: docker-test/Dockerfile.pdns
    image: pdns-server-test
    ports:
      - "5053:53"
      - "5053:53/udp"
      - "8081:8081"
    networks:
      - default
    env_file:
      - ./docker-test/env

networks:
  default:
